#!/bin/bash

# Function to display usage
display_usage() {
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check if number of arguments is less than 4
if [ $# -lt 4 ]; then
    display_usage
    exit 1
fi

# Assigning parameters to variables
file_path=$1
server_ip=$2
username=$3
ssh_key_path=$4

# Remove carriage return characters from file_path
file_path_clean=$(echo "$file_path" | tr -d '\r')

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "$ssh_key_path" "$file_path_clean" "$username@$server_ip":~/
