#!/usr/bin/env bash
# Script to set up a new Ubuntu machine with Nginx
# Configures Nginx to listen on port 80 and serve a basic page

echo -e "Updating and installing Nginx.\n"
sudo apt-get update -y -qq && \
	 sudo apt-get install nginx -y

echo -e "\nSetting up some minor stuff.\n"

# Start Nginx service
sudo service nginx start

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Grant user ownership of website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup the default index file
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Create a new index file
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restart Nginx
sudo service nginx restart

echo -e "\nSUCCESS\n"

