#!/usr/bin/env bash
# backup_mysql.sh

# Read MySQL root password from file
mysql_password=$(<"$1")

# Set the directory where the backup file will be stored
backup_dir="/home/ubuntu"

# variables for backup file
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$backup_dir/$day-$month-$year.tar.gz"

# Backup all databases and compress
mysqldump --all-databases -u root --password="$mysql_password" > "$backup_dir/backup.sql"
tar -czvf "$file_name" "$backup_dir/backup.sql"

# Securely clear the MySQL password variable
unset mysql_password
