#!/usr/bin/env bash
# backup_mysql.sh

# Read MySQL root password from file
mysql_password=$(<keyGlock)

# variables for backup file
day=$(date +"%d")
month=$(date +"%m")
year=$(date +"%Y")
file_name="$day-$month-$year.tar.gz"

# Backup specific database and compress
mysqldump -u root --password="$mysql_password" tyrell_corp nexus6 > /home/ubuntu/backup.sql
tar -czvf "/home/ubuntu/$file_name" /home/ubuntu/backup.sql

# Securely clear the MySQL password variable
unset mysql_password
