#!/usr/bin/env bash
# Sets up a server to listen on port 80 of all active IPv4 addresses
# Symbolically links the default Nginx configuration file to enable it
sudo ln -sf /etc/nginx/sites-available/default \
  /etc/nginx/sites-enabled/default
# Restarts the Nginx service to apply the changes
sudo service nginx restart
