#!/usr/bin/env bash

# Groups visitors by IP and HTTP status code, and displays this data

# Use cut to extract the IP address (first field) and status code (ninth field)
cut -d ' ' -f 1,9 apache-access.log | \
# Sort the data
sort | \
# Use uniq -c to count the occurrences of each unique line
uniq -c | \
# Sort again to display the results in descending order
sort -rn
